services:
    mppi_jax:
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        ipc: host
        ulimits:
            memlock: -1
            stack: 67108864
        stdin_open: true
        tty: true
        image: mppi_jax:latest
        command: /bin/bash
